from dash import html, dcc, Dash
import dash_bootstrap_components as dbc
import pandas as pd


class Layout:
    def __init__(self, symbol_dict: dict, countries_dict: dict) -> None:
        self._symbol_dict = symbol_dict

        self._olympics_options_dropdown = [
            {"label": name, "value": symbol} for symbol, name in symbol_dict.items()
        ]
        self._medals_options_dropdown = [
            {"label": noc, "value": country} for country, noc in countries_dict.items()
        ]
        self._countries_options = [
            {"label": noc, "value": country} for country, noc in countries_dict.items()
        ]
        self._top_bottom_options = [
            {"label": option, "value": option} for option in ("top_10", "bottom_10")
        ]
        self._season_options = [
            {"label": option, "value": option} for option in ("summer", "winter", "all")
        ]
        self._gender_options = [
            {"label": option, "value": option}
            for option in ("men", "women", "everyone")
        ]

    def layout(self):
        return dbc.Container(
            [
                dbc.NavbarSimple(
                    className="mt-4",
                    children=[
                        dbc.NavItem(dbc.NavLink(html.Img(src="assets/olympic.gif", height=80), href="#")),
                    ],
                    brand="Olympics Data Visualisation",
                    brand_href="#",
                    color="#CBDCCB",
                    
                ),
                dbc.Card(
                    id="header-card",
                    className="h-0",
                    children=[
                        dbc.CardBody(
                            dbc.Row(
                                children=[
                                    dbc.Card(
                                        dbc.CardBody(
                                            children=[
                                                dbc.Col(
                                                    dcc.Dropdown(
                                                        id="olympic-dropdown",
                                                        options=self._olympics_options_dropdown,
                                                        value="athlete",
                                                    ),
                                                    className="",
                                                    xs=12,
                                                    sm=12,
                                                    md=6,
                                                    lg=3,
                                                ),
                                            ],
                                        )
                                    )
                                ],
                            ),
                        )
                    ],
                ),
                dbc.Row(
                    className="",
                    children=[
                        dbc.Col(
                            children=[
                                dbc.Card(
                                    className="",
                                    children=[
                                        dbc.CardBody(
                                            dcc.Dropdown(
                                                id="country-picker-dropdown",
                                                options=self._countries_options,
                                                value="FRA",
                                                clearable=True,
                                            ),
                                        )
                                    ],
                                ),
                                dbc.Card(
                                    className="",
                                    children=[
                                        dbc.CardBody(
                                            dcc.Graph(
                                                id="country-info",
                                            ),
                                        )
                                    ],
                                ),
                            ],
                            xs=12,
                            sm=12,
                            md=12,
                            lg=6,
                        ),
                        dbc.Col(
                            children=[
                                dbc.Card(
                                    className="",
                                    children=[
                                        dbc.CardBody(
                                            dcc.RadioItems(
                                                id="ohlc-radio_top_bottom",
                                                className="",
                                                options=self._top_bottom_options,
                                                value="top_10",
                                            ),
                                        ),
                                    ],
                                ),
                                dbc.Card(
                                    className="",
                                    children=[
                                        dbc.CardBody(
                                            dcc.Graph(
                                                id="top_10",
                                            ),
                                        ),
                                    ],
                                ),
                            ],
                            xs=12,
                            sm=12,
                            md=12,
                            lg=6,
                        ),
                    ],
                ),
                dbc.Row(
                    className="",
                    children=[
                        dbc.Col(
                            className="",
                            children=[
                                dbc.CardBody(
                                    dcc.Graph(
                                        id="line_gender_from_start",
                                    )
                                ),
                            ],
                            xs=12,
                            sm=12,
                            md=12,
                            lg=6,
                        ),
                        dbc.Col(
                            children=[
                                dbc.Card(
                                    className="",
                                    children=[
                                        dbc.CardBody(
                                            dcc.Graph(
                                                id="general",
                                            ),
                                        ),
                                    ],
                                ),
                            ],
                            xs=12,
                            sm=12,
                            md=12,
                            lg=4,
                        ),
                        dbc.Col(
                            children=[
                                dbc.Card(
                                    className="",
                                    children=[
                                        dbc.CardBody(
                                            className="",
                                            children=[
                                                dbc.Row(
                                                    children=[
                                                        dbc.Card(
                                                            className="mb-2",
                                                            children=[
                                                                dbc.CardBody(
                                                                    dcc.Dropdown(
                                                                        id="country-picker-medals",
                                                                        options=self._medals_options_dropdown,
                                                                        value="FRA",
                                                                        clearable=True,
                                                                    ),
                                                                )
                                                            ],
                                                        ),
                                                    ]
                                                ),
                                                dbc.Row(
                                                    children=[
                                                        dbc.Card(
                                                            className="mb-2",
                                                            children=[
                                                                dbc.CardBody(
                                                                    dcc.RadioItems(
                                                                        id="ohlc-season",
                                                                        className="m-1",
                                                                        options=self._season_options,
                                                                        value="all",
                                                                    )
                                                                )
                                                            ],
                                                        )
                                                    ]
                                                ),
                                                dbc.Row(
                                                    children=[
                                                        dbc.Card(
                                                            className="",
                                                            children=[
                                                                dbc.CardBody(
                                                                    dcc.RadioItems(
                                                                        id="ohlc-gender",
                                                                        className="m-1",
                                                                        options=self._gender_options,
                                                                        value="everyone",
                                                                    )
                                                                )
                                                            ],
                                                        )
                                                    ]
                                                ),
                                            ],
                                        )
                                    ],
                                )
                            ],
                            xs=12,
                            sm=12,
                            md=12,
                            lg=2,
                        ),
                    ],
                ),
                dbc.Row(
                    className="",
                    children=[
                        dbc.Col(
                            className="",
                            children=[
                                dbc.Card(
                                    className="",
                                    children=[
                                        dbc.CardBody(
                                            className="",
                                            children=[
                                                dbc.Row(
                                                    dbc.Card(
                                                        className="",
                                                        children=[
                                                            dbc.CardBody(
                                                                className="",
                                                                children=[
                                                                    dcc.Graph(
                                                                        id="yearly-participation",
                                                                    ),
                                                                ],
                                                            )
                                                        ],
                                                    )
                                                ),
                                                dbc.Row(
                                                    dbc.Card(
                                                        className="",
                                                        children=[
                                                            dbc.CardBody(
                                                                className="",
                                                                children=[
                                                                    dcc.RangeSlider(
                                                                        id="year-range",
                                                                        min=1896,
                                                                        max=2016,
                                                                        step=2,
                                                                        marks=None,
                                                                        value=[
                                                                            1936,
                                                                            1980,
                                                                        ],
                                                                        tooltip={"placement": "bottom", "always_visible": True}
                                                                    ),
                                                                ],
                                                            )
                                                        ],
                                                    )
                                                ),
                                            ],
                                        )
                                    ],
                                )
                            ],
                            xs=12,
                            sm=12,
                            md=12,
                            lg=8,
                        ),
                        dbc.Col(
                            className="",
                            children=[
                                dbc.Card(
                                    className="",
                                    children=[
                                        dbc.CardBody(
                                            className="",
                                            children=[
                                                dcc.Graph(
                                                    id="burst",
                                                ),
                                            ],
                                        )
                                    ],
                                )
                            ],
                            xs=12,
                            sm=12,
                            md=12,
                            lg=4,
                        ),
                    ],
                ),
                dbc.Row(
                    className="my-5 mx-4",
                    children=[
                        dbc.CardFooter(
                            className="",
                            children=[
                                html.H5("Cyrille Kolle"),
                                html.H6("IT-Högskolan, Dec 2022"),
                            ],
                        )
                    ],
                ),
                # storing intermediate value on clients browser in order to share between several callbacks
                dcc.Store(id="filtered-df"),
            ],
            fluid=True,
        )
